### ISSUE TITLE
Thats not how you make versions in github

### ISSUE THREAD

**Issue by Kaffeedor** [GozZzer/Light#3]
![image](https://user-images.githubusercontent.com/49571205/121479822-b7d99980-c9ca-11eb-8171-09b5be1a5d10.png)
thats not how you make versions in github, this should include a short information about the changes, versions can be made here:
![image](https://user-images.githubusercontent.com/49571205/121479992-e35c8400-c9ca-11eb-9904-6a9eddaa4fbf.png)

**Comment by Kaffeedor** [comment]
closed this

**Comment by GozZzer** [comment]
I close it
